server:
  port: 8081
spring:
  application:
    name: leadnews-article
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        service: leadnews-article
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yaml
  rabbitmq:
    listener:
      simple:
        prefetch: 1
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password: 123456

snowflake:
  data-center-id: 1
  machine-id: 1



